{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ldap-2fa-backend.serviceAccountName" . }}
  labels:
    {{- include "ldap-2fa-backend.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.serviceAccountIAM.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccountIAM.roleArn | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
